### ISSUE TITLE
- Infinity title

### ISSUE THREAD

**Issue by xGronox** [Saudade-Studio-RU/Desiderium-Dedicated-Server#3]
> Лог [latest.log](https://github.com/Saudade-Studio-RU/Desiderium-Dedicated-Server/files/13878742/latest.log)

> Ошибка: На экране после захода остаётся текст -
![image](https://github.com/Saudade-Studio-RU/Desiderium-Dedicated-Server/assets/91997265/443ba56e-9051-4acb-b4b0-8812d8c69ffb)

> В логе заход [09Jan2024 17:17:47.097] < ищи по поиску это

**Comment by xGronox** [comment]
> Добавляю, у игрока решилась проблема тем что переустановил полностью Forked сборку.

**Comment by krupta** [comment]
@yShe4Ka спроси у мододела как вызывается этот текст, и может ли он такое починить ?

**Comment by krupta** [comment]
вроде починено
