### ISSUE TITLE
Desiderium Bugs

### ISSUE THREAD

**Issue by Pers1ks** [Saudade-Studio-RU/Desiderium-Dedicated-Server#5]
Может кто сталкивался с такой проблемой, что просеиватель не работает? Сборка Desiderium для майнкрафт. Играем с мужем, но ни у меня, ни у него не работает просеиватель, как ни крути.

И еще плод демона тоже через раз работает..

Спасибо за ответ заранее

**Comment by krupta** [comment]
ответили тему в дискорде
