### ISSUE TITLE
Где контроль версий?

### ISSUE THREAD

**Issue by GIKExe** [Saudade-Studio-RU/Desiderium-Dedicated-Server#8]
Крашит майн при заходе. Сервер на forge 40.2.10 а клиент 40.2.7, 40.2.14, 40.2.17...
Где найти клиент 40.2.10 или сервер 40.2.17 ?

**Comment by krupta** [comment]
@GIKExe Сервер и клиент на разных версиях форджа нормально работают между собой 
На клиент ставится фордж который написан в инструкции (если он у вас не запускается то сборка не правильно установлена)
В вики написано какой клиент и сервер между собой использовать (там вообще всё написано, что нужно)
